name: flutter_network
description: "Adsplatter's Flutter network package"
version: 1.0.0
repository: https://github.com/adsplatter/flutter-network
homepage: https://github.com/adsplatter/flutter-network
issue_tracker: https://github.com/adsplatter/flutter-network/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # HTTP Package
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
